// Code generated by hertz generator.

package auth

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	auth "github.com/zy84338719/upftp/biz/model/auth"
)

// Authenticate .
// @router /api/auth [POST]
func Authenticate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.AuthRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(auth.AuthResponse)

	c.JSON(consts.StatusOK, resp)
}
