// Code generated by hertz generator.

package settings

import (
	"context"
	"encoding/json"
	"sync"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	settings "github.com/zy84338719/upftp/biz/model/settings"
	"github.com/zy84338719/upftp/biz/service/file"
	"github.com/zy84338719/upftp/pkg/conf"
	"github.com/zy84338719/upftp/pkg/logger"
)

// 延迟初始化Service实例
var (
	svc     *file.Service
	svcOnce sync.Once
)

func getService() *file.Service {
	svcOnce.Do(func() {
		svc = file.NewService(conf.AppConfig)
	})
	return svc
}

// HandleGetSettings .
// @router /api/settings [GET]
func HandleGetSettings(ctx context.Context, c *app.RequestContext) {
	var err error
	var req settings.GetSettingsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	cfg := conf.AppConfig

	// 返回完整的设置（不包含密码）
	settingsMap := map[string]interface{}{
		"ftpUser":      cfg.Username,
		"enableFTP":    cfg.EnableFTP,
		"enableMCP":    cfg.EnableMCP,
		"enableWebDAV": cfg.EnableWebDAV,
		"enableNFS":    cfg.EnableNFS,
		"ftpPort":      cfg.GetFTPPort(),
		"webDAVPort":   cfg.GetWebDAVPort(),
		"nfsPort":      cfg.GetNFSPort(),
		"httpAuthOn":   cfg.HTTPAuth.Enabled,
	}

	// 直接返回完整的 JSON，不使用 thrift 生成的结构体
	c.JSON(consts.StatusOK, map[string]interface{}{
		"settings": settingsMap,
	})
}

// HandleSetLanguage .
// @router /api/settings/language [POST]
func HandleSetLanguage(ctx context.Context, c *app.RequestContext) {
	var err error
	var req settings.SetLanguageRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	body, err := c.Body()
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	var langReq struct {
		Language string `json:"language"`
	}
	if err := json.Unmarshal(body, &langReq); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	if err := getService().Config().SetLanguage(langReq.Language); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid language"})
		return
	}

	resp := &settings.SetLanguageResponse{
		Success: true,
	}
	c.JSON(consts.StatusOK, resp)
}

// HandleSetFTP .
// @router /api/settings/ftp [POST]
func HandleSetFTP(ctx context.Context, c *app.RequestContext) {
	var err error
	var req settings.SetFTPRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	body, err := c.Body()
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	var ftpReq struct {
		Username string `json:"username"`
		Password string `json:"password"`
	}
	if err := json.Unmarshal(body, &ftpReq); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	svc := getService()
	if ftpReq.Username != "" {
		svc.Config().Username = ftpReq.Username
	}
	if ftpReq.Password != "" {
		svc.Config().Password = ftpReq.Password
	}

	logger.Info("FTP settings updated")
	resp := &settings.SetFTPResponse{
		Success: true,
	}
	c.JSON(consts.StatusOK, resp)
}

// HandleSetServices .
// @router /api/settings/services [POST]
func HandleSetServices(ctx context.Context, c *app.RequestContext) {
	body, err := c.Body()
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	var servicesReq struct {
		EnableFTP    bool   `json:"enableFTP"`
		EnableMCP    bool   `json:"enableMCP"`
		EnableWebDAV bool   `json:"enableWebDAV"`
		EnableNFS    bool   `json:"enableNFS"`
		FTPPort      string `json:"ftpPort"`
		WebDAVPort   string `json:"webDAVPort"`
		NFSPort      string `json:"nfsPort"`
		MCPPort      string `json:"mcpPort"`
	}
	if err := json.Unmarshal(body, &servicesReq); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	svc := getService()
	cfg := svc.Config()

	// 更新配置
	cfg.EnableFTP = servicesReq.EnableFTP
	cfg.EnableMCP = servicesReq.EnableMCP
	cfg.EnableWebDAV = servicesReq.EnableWebDAV
	cfg.EnableNFS = servicesReq.EnableNFS

	if servicesReq.FTPPort != "" {
		cfg.SetFTPPort(servicesReq.FTPPort)
	}
	if servicesReq.WebDAVPort != "" {
		cfg.WebDAVPort = ":" + servicesReq.WebDAVPort
	}
	if servicesReq.NFSPort != "" {
		cfg.NFSPort = ":" + servicesReq.NFSPort
	}

	// 保存配置到文件
	if err := conf.SaveConfig(); err != nil {
		logger.Error("Failed to save config: %v", err)
	}

	logger.Info("Services settings updated")

	// 直接返回完整的 JSON
	c.JSON(consts.StatusOK, map[string]interface{}{
		"success": true,
	})
}
