// Code generated by hertz generator.

package settings

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	settings "github.com/zy84338719/upftp/biz/model/settings"
	"github.com/zy84338719/upftp/biz/service/file"
	"github.com/zy84338719/upftp/pkg/conf"
	"github.com/zy84338719/upftp/pkg/logger"
)

// 初始化Service实例
var svc = file.NewService(conf.AppConfig)

// HandleGetSettings .
// @router /api/settings [GET]
func HandleGetSettings(ctx context.Context, c *app.RequestContext) {
	var err error
	var req settings.GetSettingsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	info := svc.GetServerInfo()
	// 转换为 map[string]string
	infoStr := make(map[string]string)
	for k, v := range info {
		infoStr[k] = fmt.Sprintf("%v", v)
	}
	resp := &settings.GetSettingsResponse{
		Settings: infoStr,
	}
	c.JSON(consts.StatusOK, resp)
}

// HandleSetLanguage .
// @router /api/settings/language [POST]
func HandleSetLanguage(ctx context.Context, c *app.RequestContext) {
	var err error
	var req settings.SetLanguageRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	body, err := c.Body()
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	var langReq struct {
		Language string `json:"language"`
	}
	if err := json.Unmarshal(body, &langReq); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	if err := svc.Config().SetLanguage(langReq.Language); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid language"})
		return
	}

	resp := &settings.SetLanguageResponse{
		Success: true,
	}
	c.JSON(consts.StatusOK, resp)
}

// HandleSetHTTPAuth .
// @router /api/settings/http-auth [POST]
func HandleSetHTTPAuth(ctx context.Context, c *app.RequestContext) {
	var err error
	var req settings.SetHTTPAuthRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	body, err := c.Body()
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	var authReq struct {
		Enabled  bool   `json:"enabled"`
		Username string `json:"username"`
		Password string `json:"password"`
	}
	if err := json.Unmarshal(body, &authReq); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	svc.Config().HTTPAuth.Enabled = authReq.Enabled
	if authReq.Username != "" {
		svc.Config().HTTPAuth.Username = authReq.Username
	}
	if authReq.Password != "" {
		svc.Config().HTTPAuth.Password = authReq.Password
	}

	logger.Info("HTTP auth settings updated")
	resp := &settings.SetHTTPAuthResponse{
		Success: true,
	}
	c.JSON(consts.StatusOK, resp)
}

// HandleSetFTP .
// @router /api/settings/ftp [POST]
func HandleSetFTP(ctx context.Context, c *app.RequestContext) {
	var err error
	var req settings.SetFTPRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	body, err := c.Body()
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	var ftpReq struct {
		Username string `json:"username"`
		Password string `json:"password"`
	}
	if err := json.Unmarshal(body, &ftpReq); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	if ftpReq.Username != "" {
		svc.Config().Username = ftpReq.Username
	}
	if ftpReq.Password != "" {
		svc.Config().Password = ftpReq.Password
	}

	logger.Info("FTP settings updated")
	resp := &settings.SetFTPResponse{
		Success: true,
	}
	c.JSON(consts.StatusOK, resp)
}
