// Code generated by hertz generator.

package fileops

import (
	"context"
	"encoding/json"
	"fmt"
	"path/filepath"
	"sync"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	fileops "github.com/zy84338719/upftp/biz/model/fileops"
	"github.com/zy84338719/upftp/biz/service/file"
	"github.com/zy84338719/upftp/pkg/conf"
	"github.com/zy84338719/upftp/pkg/logger"
)

// 延迟初始化Service实例
var (
	svc     *file.Service
	svcOnce sync.Once
)

func getService() *file.Service {
	svcOnce.Do(func() {
		svc = file.NewService(conf.AppConfig)
	})
	return svc
}

// checkAuth 检查用户是否已登录（如果HTTP认证启用）
func checkAuth(c *app.RequestContext) bool {
	// 如果HTTP认证未启用，允许上传
	if !conf.AppConfig.HTTPAuth.Enabled {
		return true
	}

	// 检查请求中是否有认证信息
	username, password, ok := c.Request.BasicAuth()
	if !ok {
		return false
	}

	// 验证用户名密码
	return username == conf.AppConfig.HTTPAuth.Username && password == conf.AppConfig.HTTPAuth.Password
}

// HandleUpload .
// @router /api/upload [POST]
func HandleUpload(ctx context.Context, c *app.RequestContext) {
	var err error
	var req fileops.WebUploadFileRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 检查认证
	if !checkAuth(c) {
		c.Header("WWW-Authenticate", `Basic realm="UPFTP"`)
		c.JSON(consts.StatusUnauthorized, map[string]string{"error": "Authentication required"})
		return
	}

	svc := getService()

	if !svc.UploadEnabled() {
		c.JSON(consts.StatusForbidden, map[string]string{"error": "Upload disabled"})
		return
	}

	form, err := c.MultipartForm()
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": fmt.Sprintf("Failed to parse form: %s", err.Error())})
		return
	}

	uploadPath := form.Value["path"]
	targetPath := "/"
	if len(uploadPath) > 0 && uploadPath[0] != "" {
		targetPath = uploadPath[0]
	}

	files := form.File["files"]
	if len(files) == 0 {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "No files uploaded"})
		return
	}

	var uploaded []string
	for _, fileHeader := range files {
		file, err := fileHeader.Open()
		if err != nil {
			logger.Error("Failed to open uploaded file %s: %v", fileHeader.Filename, err)
			continue
		}

		fullPath := filepath.Join(targetPath, fileHeader.Filename)
		if err := svc.Upload(fullPath, file, fileHeader.Size); err != nil {
			logger.Error("Upload error for %s: %v", fileHeader.Filename, err)
			file.Close()
			continue
		}
		file.Close()
		uploaded = append(uploaded, fileHeader.Filename)
		logger.Info("Uploaded: %s", filepath.Join(targetPath, fileHeader.Filename))
	}

	resp := &fileops.WebUploadFileResponse{
		Success:  true,
		Uploaded: uploaded,
		Count:    int32(len(uploaded)),
	}
	c.JSON(consts.StatusOK, resp)
}

// HandleCreateFolder .
// @router /api/create-folder [POST]
func HandleCreateFolder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req fileops.WebCreateFolderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 检查认证
	if !checkAuth(c) {
		c.Header("WWW-Authenticate", `Basic realm="UPFTP"`)
		c.JSON(consts.StatusUnauthorized, map[string]string{"error": "Authentication required"})
		return
	}

	body, err := c.Body()
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	var folderReq struct {
		Path string `json:"path"`
		Name string `json:"name"`
	}
	if err := json.Unmarshal(body, &folderReq); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	folderPath := filepath.Join(folderReq.Path, folderReq.Name)
	if err := getService().CreateFolder(folderPath); err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}

	logger.Info("Created folder: %s", folderPath)
	resp := &fileops.WebCreateFolderResponse{
		Success: true,
	}
	c.JSON(consts.StatusOK, resp)
}

// HandleDelete .
// @router /api/delete [POST]
func HandleDelete(ctx context.Context, c *app.RequestContext) {
	var err error
	var req fileops.WebDeleteFileRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 检查认证
	if !checkAuth(c) {
		c.Header("WWW-Authenticate", `Basic realm="UPFTP"`)
		c.JSON(consts.StatusUnauthorized, map[string]string{"error": "Authentication required"})
		return
	}

	body, err := c.Body()
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}
	var deleteReq struct {
		Path string `json:"path"`
	}
	if err := json.Unmarshal(body, &deleteReq); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	if err := getService().Delete(deleteReq.Path); err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}

	logger.Info("Deleted: %s", deleteReq.Path)
	resp := &fileops.WebDeleteFileResponse{
		Success: true,
	}
	c.JSON(consts.StatusOK, resp)
}

// HandleRename .
// @router /api/rename [POST]
func HandleRename(ctx context.Context, c *app.RequestContext) {
	var err error
	var req fileops.WebRenameFileRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 检查认证
	if !checkAuth(c) {
		c.Header("WWW-Authenticate", `Basic realm="UPFTP"`)
		c.JSON(consts.StatusUnauthorized, map[string]string{"error": "Authentication required"})
		return
	}

	body, err := c.Body()
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	var renameReq struct {
		Path    string `json:"path"`
		NewName string `json:"newName"`
	}
	if err := json.Unmarshal(body, &renameReq); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "Invalid request"})
		return
	}

	if err := getService().Rename(renameReq.Path, renameReq.NewName); err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}

	logger.Info("Renamed: %s -> %s", renameReq.Path, renameReq.NewName)
	resp := &fileops.WebRenameFileResponse{
		Success: true,
	}
	c.JSON(consts.StatusOK, resp)
}
