// Code generated by hertz generator.

package settings

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/zy84338719/upftp/pkg/conf"
	"github.com/zy84338719/upftp/pkg/middleware"
)

func rootMw() []app.HandlerFunc {
	// 全局中间件：恢复、CORS、认证
	return []app.HandlerFunc{
		middleware.RecoveryMiddleware(),
		middleware.CORSMiddleware(),
		middleware.AuthMiddleware(conf.AppConfig),
	}
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _settingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handlegetsettingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handlesetftpMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handlesetlanguageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handlesetservicesMw() []app.HandlerFunc {
	// your code...
	return nil
}
