// Code generated by hertz generator.

package index

import (
	"context"
	"encoding/json"
	"fmt"
	"html/template"
	"net/url"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/skip2/go-qrcode"
	index "github.com/zy84338719/upftp/biz/model/index"
	"github.com/zy84338719/upftp/biz/service/file"
	"github.com/zy84338719/upftp/pkg/conf"
	"github.com/zy84338719/upftp/pkg/file/model"
	"github.com/zy84338719/upftp/pkg/logger"
)

// 初始化Service实例
var svc = file.NewService(conf.AppConfig)

// HandleIndexPage .
// @router / [GET]
func HandleIndexPage(ctx context.Context, c *app.RequestContext) {
	legacyFiles, err := svc.ListFilesLegacy("/")
	if err != nil {
		logger.Error("Failed to list root files: %v", err)
		legacyFiles = []model.LegacyFileInfo{}
	}

	data := svc.GetIndexPageData(legacyFiles)

	funcMap := template.FuncMap{
		"json": func(v interface{}) template.JS {
			b, _ := json.Marshal(v)
			return template.JS(b)
		},
	}

	tmpl, err := template.New("index").Funcs(funcMap).ParseFS(getTemplatesFS(), "index.html")
	if err != nil {
		c.String(consts.StatusInternalServerError, "Template parse error: "+err.Error())
		logger.Error("Failed to parse index template: %v", err)
		return
	}

	c.Header("Content-Type", "text/html; charset=utf-8")
	if err := tmpl.Execute(c.Response.BodyWriter(), data); err != nil {
		logger.Error("Failed to execute index template: %v", err)
	}
}

// HandleServerInfo .
// @router /api/info [GET]
func HandleServerInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req index.GetServerInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	info := svc.GetServerInfo()
	// 转换为 map[string]string
	infoStr := make(map[string]string)
	for k, v := range info {
		infoStr[k] = fmt.Sprintf("%v", v)
	}
	resp := &index.GetServerInfoResponse{
		Info: infoStr,
	}
	c.JSON(consts.StatusOK, resp)
}

// HandleFileListAPI .
// @router /api/files [GET]
func HandleFileListAPI(ctx context.Context, c *app.RequestContext) {
	var err error
	var req index.ListFilesLegacyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	path := c.DefaultQuery("path", "/")
	if path == "" {
		path = "/"
	}

	files, err := svc.ListFilesLegacy(path)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	// 转换为响应格式
	fileList := make([]map[string]string, 0, len(files))
	for _, f := range files {
		fileList = append(fileList, map[string]string{
			"name":    f.Name,
			"size":    f.Size,
			"modTime": f.ModTime,
			"isDir":   strconv.FormatBool(f.IsDir),
		})
	}

	resp := &index.ListFilesLegacyResponse{
		Files: fileList,
	}
	c.JSON(consts.StatusOK, resp)
}

// HandleDirectoryTree .
// @router /api/tree [GET]
func HandleDirectoryTree(ctx context.Context, c *app.RequestContext) {
	var err error
	var req index.GetDirectoryTreeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	path := c.DefaultQuery("path", "/")
	if path == "" {
		path = "/"
	}

	tree, err := svc.BuildTree(path, 0)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	// 转换为 map 格式
	treeMap := treeToMap(tree)

	resp := &index.GetDirectoryTreeResponse{
		Tree: treeMap,
	}
	c.JSON(consts.StatusOK, resp)
}

// HandleQRCode .
// @router /api/qrcode [GET]
func HandleQRCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req index.GetQRCodeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	rawURL := c.DefaultQuery("url", "")
	if rawURL == "" {
		c.String(consts.StatusBadRequest, "missing url parameter")
		return
	}

	parsed, err := url.Parse(rawURL)
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") {
		c.String(consts.StatusBadRequest, "invalid url")
		return
	}

	png, err := qrcode.Encode(rawURL, qrcode.Medium, 256)
	if err != nil {
		logger.Error("QR code generation error: %v", err)
		c.String(consts.StatusInternalServerError, "failed to generate QR code")
		return
	}

	c.Header("Content-Type", "image/png")
	c.SetStatusCode(consts.StatusOK)
	c.Response.BodyWriter().Write(png)
}

// treeToMap 将 TreeNode 转换为 map[string]string
func treeToMap(node *model.TreeNode) map[string]string {
	if node == nil {
		return map[string]string{}
	}
	return map[string]string{
		"name":  node.Name,
		"path":  node.Path,
		"isDir": "true",
	}
}
