// Code generated by hertz generator. DO NOT EDIT.

package download

import "github.com/cloudwego/hertz/pkg/app"

// _handledownloadMw 是 HandleDownload 的 middleware
func _handledownloadMw() []app.HandlerFunc {
	return nil
}

// rootMw 是根路由的 middleware
func rootMw() []app.HandlerFunc {
	return nil
}

func _downloadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _download0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
