// Code generated by hertz generator.

package file

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	file "github.com/zy84338719/upftp/biz/model/file"
)

// ListFiles .
// @router /api/file/list [GET]
func ListFiles(ctx context.Context, c *app.RequestContext) {
	var err error
	var req file.ListFilesRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(file.ListFilesResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetFile .
// @router /api/file/get [GET]
func GetFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req file.GetFileRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(file.GetFileResponse)

	c.JSON(consts.StatusOK, resp)
}

// UploadFile .
// @router /api/file/upload [POST]
func UploadFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req file.UploadFileRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(file.UploadFileResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteFile .
// @router /api/file/delete [DELETE]
func DeleteFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req file.DeleteFileRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(file.DeleteFileResponse)

	c.JSON(consts.StatusOK, resp)
}
