// Code generated by hertz generator.

package download

import (
	"archive/zip"
	"bytes"
	"context"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/zy84338719/upftp/pkg/conf"
	"github.com/zy84338719/upftp/pkg/logger"
)

// Download .
// @router /download/*filepath [GET]
func Download(ctx context.Context, c *app.RequestContext) {
	// 获取文件路径
	filePath := c.Param("filepath")
	if filePath == "" {
		c.String(consts.StatusBadRequest, "File path is required")
		return
	}

	// 清理路径，防止目录遍历攻击
	filePath = strings.TrimPrefix(filePath, "/")
	filePath = strings.TrimPrefix(filePath, "./")
	filePath = strings.TrimPrefix(filePath, "../")

	// 构建完整路径
	rootPath := conf.AppConfig.Root
	if rootPath == "" {
		rootPath = "."
	}

	fullPath := filepath.Join(rootPath, filePath)

	// 检查文件是否存在
	info, err := os.Stat(fullPath)
	if err != nil {
		if os.IsNotExist(err) {
			logger.Error("File not found: %s", fullPath)
			c.String(consts.StatusNotFound, "File not found")
			return
		}
		logger.Error("Failed to stat file: %v", err)
		c.String(consts.StatusInternalServerError, "Internal server error")
		return
	}

	// 如果是目录，返回 zip 下载
	if info.IsDir() {
		// 创建 zip 压缩包
		buf := new(bytes.Buffer)
		zipWriter := zip.NewWriter(buf)

		baseName := filepath.Base(fullPath)
		if baseName == "" || baseName == "." {
			baseName = "download"
		}

		err := filepath.Walk(fullPath, func(path string, info fs.FileInfo, err error) error {
			if err != nil {
				return err
			}

			// 计算相对路径
			relPath, err := filepath.Rel(fullPath, path)
			if err != nil {
				return err
			}

			// 在 zip 中的路径
			zipPath := filepath.Join(baseName, relPath)

			if info.IsDir() {
				// 创建目录条目
				_, err := zipWriter.Create(zipPath + "/")
				if err != nil {
					return fmt.Errorf("failed to create directory in zip: %w", err)
				}
				return nil
			}

			// 创建文件条目
			writer, err := zipWriter.Create(zipPath)
			if err != nil {
				return fmt.Errorf("failed to create file in zip: %w", err)
			}

			// 读取文件内容
			file, err := os.Open(path)
			if err != nil {
				return fmt.Errorf("failed to open file: %w", err)
			}
			defer file.Close()

			fileBytes, err := os.ReadFile(path)
			if err != nil {
				return fmt.Errorf("failed to read file: %w", err)
			}

			_, err = writer.Write(fileBytes)
			if err != nil {
				return fmt.Errorf("failed to write file to zip: %w", err)
			}

			return nil
		})

		if err != nil {
			logger.Error("Failed to create zip: %v", err)
			c.String(consts.StatusInternalServerError, "Failed to create zip archive")
			return
		}

		// 关闭 zip writer
		err = zipWriter.Close()
		if err != nil {
			logger.Error("Failed to close zip: %v", err)
			c.String(consts.StatusInternalServerError, "Failed to finalize zip archive")
			return
		}

		// 设置响应头
		timestamp := time.Now().Format("20060102-150405")
		zipName := fmt.Sprintf("%s-%s.zip", baseName, timestamp)
		c.Header("Content-Type", "application/zip")
		c.Header("Content-Disposition", fmt.Sprintf("attachment; filename=\"%s\"", zipName))
		c.Header("Content-Length", fmt.Sprintf("%d", buf.Len()))
		c.SetStatusCode(consts.StatusOK)
		c.Response.BodyWriter().Write(buf.Bytes())
		return
	}

	// 读取文件内容
	data, err := os.ReadFile(fullPath)
	if err != nil {
		logger.Error("Failed to read file: %v", err)
		c.String(consts.StatusInternalServerError, "Failed to read file")
		return
	}

	// 设置 Content-Type
	contentType := getContentType(fullPath)
	c.Header("Content-Type", contentType)
	c.Header("Content-Disposition", "attachment; filename=\""+filepath.Base(filePath)+"\"")
	c.SetStatusCode(consts.StatusOK)
	c.Response.BodyWriter().Write(data)
}

// getContentType 根据文件扩展名返回 Content-Type
func getContentType(filePath string) string {
	ext := strings.ToLower(filepath.Ext(filePath))
	switch ext {
	case ".html", ".htm":
		return "text/html"
	case ".css":
		return "text/css"
	case ".js":
		return "application/javascript"
	case ".json":
		return "application/json"
	case ".png":
		return "image/png"
	case ".jpg", ".jpeg":
		return "image/jpeg"
	case ".gif":
		return "image/gif"
	case ".svg":
		return "image/svg+xml"
	case ".ico":
		return "image/x-icon"
	case ".pdf":
		return "application/pdf"
	case ".txt":
		return "text/plain"
	case ".md":
		return "text/markdown"
	case ".xml":
		return "application/xml"
	case ".zip":
		return "application/zip"
	case ".mp4":
		return "video/mp4"
	case ".mp3":
		return "audio/mpeg"
	case ".webm":
		return "video/webm"
	case ".wav":
		return "audio/wav"
	default:
		return "application/octet-stream"
	}
}
