// Code generated by hertz generator.

package system

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/zy84338719/upftp/pkg/conf"
	"github.com/zy84338719/upftp/pkg/middleware"
)

func rootMw() []app.HandlerFunc {
	// 全局中间件：恢复、CORS、认证
	return []app.HandlerFunc{
		middleware.RecoveryMiddleware(),
		middleware.CORSMiddleware(),
		middleware.AuthMiddleware(conf.AppConfig),
	}
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _startserverMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getserverstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stopserverMw() []app.HandlerFunc {
	// your code...
	return nil
}
