// Code generated by hertz generator.

package auth

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/zy84338719/upftp/pkg/middleware"
)

func rootMw() []app.HandlerFunc {
	// 登录相关接口不需要认证中间件，但需要有恢复和CORS
	return []app.HandlerFunc{
		middleware.RecoveryMiddleware(),
		middleware.CORSMiddleware(),
	}
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authenticateMw() []app.HandlerFunc {
	// your code...
	return nil
}
