// Code generated by hertz generator.

package system

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	system "github.com/zy84338719/upftp/biz/model/system"
)

// GetServerStatus .
// @router /api/system/status [GET]
func GetServerStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req system.GetServerStatusRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(system.GetServerStatusResponse)

	c.JSON(consts.StatusOK, resp)
}

// StartServer .
// @router /api/system/start [POST]
func StartServer(ctx context.Context, c *app.RequestContext) {
	var err error
	var req system.StartServerRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(system.StartServerResponse)

	c.JSON(consts.StatusOK, resp)
}

// StopServer .
// @router /api/system/stop [POST]
func StopServer(ctx context.Context, c *app.RequestContext) {
	var err error
	var req system.StopServerRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(system.StopServerResponse)

	c.JSON(consts.StatusOK, resp)
}
