// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	account "github.com/zy84338719/upftp/biz/router/account"
	auth "github.com/zy84338719/upftp/biz/router/auth"
	download "github.com/zy84338719/upftp/biz/router/download"
	file "github.com/zy84338719/upftp/biz/router/file"
	fileops "github.com/zy84338719/upftp/biz/router/fileops"
	index "github.com/zy84338719/upftp/biz/router/index"
	settings "github.com/zy84338719/upftp/biz/router/settings"
	system "github.com/zy84338719/upftp/biz/router/system"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	system.Register(r)

	settings.Register(r)

	fileops.Register(r)

	file.Register(r)

	account.Register(r)

	auth.Register(r)

	download.Register(r)

	index.Register(r)
}
