name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

  publish-packages:
    needs: goreleaser
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          
      - name: Setup APT repository
        run: |
          # This would typically sync to your private APT repository
          # For now, we'll just show the structure
          echo "Setting up APT repository structure..."
          mkdir -p apt-repo/{pool/main,dists/stable/main}
          find artifacts/ -name "*.deb" -exec cp {} apt-repo/pool/main/ \; || true
          ls -la apt-repo/pool/main/ || true
          
      - name: Upload to private repository
        run: |
          echo "In a real scenario, this would:"
          echo "1. Upload .deb packages to your private APT repository"
          echo "2. Update Homebrew tap repository"
          echo "3. Notify package management systems"
          echo ""
          echo "Files that would be uploaded:"
          find artifacts/ -name "*.deb" -o -name "*.rpm" || true
