// Code generated by hertz generator.

package index

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/zy84338719/upftp/pkg/conf"
	"github.com/zy84338719/upftp/pkg/middleware"
)

func rootMw() []app.HandlerFunc {
	// 全局中间件：恢复、CORS、认证
	return []app.HandlerFunc{
		middleware.RecoveryMiddleware(),
		middleware.CORSMiddleware(),
		middleware.AuthMiddleware(conf.AppConfig),
	}
}

func _handleindexpageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handlefilelistapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handleserverinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handleqrcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handledirectorytreeMw() []app.HandlerFunc {
	// your code...
	return nil
}
